version: "2"
services:
  web:
    container_name: order_service
    build: .
    ports:
      - "4002:4002"
    links:
      - mongo
  mongo:
    container_name: order_mongo
    image: mongo
    ports:
      - "27017:27017"